services:
  db:
    image: postgres
    volumes:
      - ./db/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: >
              bash -c "
              if [ -f /app/tmp/pids/server.pid ]; then
                rm /app/tmp/pids/server.pid;
              fi &&
              bundle install &&
              yarn install && yarn build && yarn build:css &&
              bundle exec rails s -p 3000 -b '0.0.0.0'
              "
    volumes:
      - .:/app
      - bundle_data:/app/vendor/bundle
    environment:
      - NODE_ENV=development
      - CSS_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres_data:
  bundle_data:
  node_modules: